/**
 * GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by vjs-compiler.
 * Source: packages/react/react/src/skins/toasted/MediaSkinToasted.tsx
 * Pipeline: skin-web-component-inline
 *
 * To regenerate, run:
 * packages/build-tools/vjs-compiler/dist/cli.js compile \
 *   packages/react/react/src/skins/toasted/MediaSkinToasted.tsx \
 *   --type skin --format web-component --css inline \
 *   --out-dir packages/html/html/src/skins/compiled/inline/
 */

import { MediaSkin } from '../../../media-skin';
import '../../../components/media-current-time-display';
import '../../../components/media-duration-display';
import '../../../components/media-fullscreen-button';
import '../../../media-container';
import '../../../components/media-mute-button';
import '../../../components/media-play-button';
import '../../../components/media-time-range';
import '../../../components/media-volume-range';
import '@vjs-10/html-icons';

export function getTemplateHTML() {
  return /* html */ `
    ${MediaSkin.getTemplateHTML()}
    <style>
      /* TODO: Add skin styles here */
    </style>
    <media-container>
      <slot name="media" slot="media"></slot>
      <div class="controls" data-testid="media-controls">
        <div class="controls-row">
          <media-time-range-root class="slider-root">
            <media-time-range-track class="slider-track">
              <media-time-range-progress class="slider-progress"></media-time-range-progress>
              <media-time-range-pointer class="slider-pointer"></media-time-range-pointer>
            </media-time-range-track>
            <media-time-range-thumb class="slider-thumb time-slider-thumb"></media-time-range-thumb>
          </media-time-range-root>
        </div>
        <div class="controls-row">
          <div class="flex items-center gap-3">
            <media-play-button class="button icon-button">
              <media-play-icon></media-play-icon>
              <media-pause-icon></media-pause-icon>
            </media-play-button>
            <div class="flex items-center gap-1">
              <media-current-time-display class="time-display"></media-current-time-display>
              <span class="opacity-50">/</span>
              <media-duration-display class="time-display opacity-50"></media-duration-display>
            </div>
          </div>
          <div class="flex items-center gap-0.5">
            <div class="volume-controls">
              <media-mute-button class="button icon-button volume-button">
                <media-volume-high-icon></media-volume-high-icon>
                <media-volume-low-icon></media-volume-low-icon>
                <media-volume-off-icon></media-volume-off-icon>
              </media-mute-button>
              <div class="volume-slider">
                <media-volume-range-root class="slider-root">
                  <media-volume-range-track class="slider-track">
                    <media-volume-range-progress class="slider-progress"></media-volume-range-progress>
                  </media-volume-range-track>
                  <media-volume-range-thumb class="slider-thumb"></media-volume-range-thumb>
                </media-volume-range-root>
              </div>
            </div>
            <media-fullscreen-button class="button icon-button">
              <media-fullscreen-enter-icon></media-fullscreen-enter-icon>
              <media-fullscreen-exit-icon></media-fullscreen-exit-icon>
            </media-fullscreen-button>
          </div>
        </div>
      </div>
    </media-container>
  `;
}

export class MediaSkinToastedCompiled extends MediaSkin {
  static getTemplateHTML: () => string = getTemplateHTML;
}

customElements.define('media-skin-toasted-compiled', MediaSkinToastedCompiled);
