/**
 * GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by vjs-compiler.
 * Source: packages/react/react/src/skins/default/MediaSkinDefault.tsx
 * Pipeline: skin-web-component-inline
 *
 * To regenerate, run:
 * packages/build-tools/vjs-compiler/dist/cli.js compile \
 *   packages/react/react/src/skins/default/MediaSkinDefault.tsx \
 *   --type skin --format web-component --css inline \
 *   --out-dir packages/html/html/src/skins/compiled/inline/
 */

import { MediaSkin } from '../../../media-skin';
import '../../../components/media-current-time-display';
import '../../../components/media-duration-display';
import '../../../components/media-fullscreen-button';
import '../../../media-container';
import '../../../components/media-mute-button';
import '../../../components/media-popover';
import '../../../components/media-play-button';
import '../../../components/media-time-range';
import '../../../components/media-volume-range';
import '@vjs-10/html-icons';

export function getTemplateHTML() {
  return /* html */ `
    ${MediaSkin.getTemplateHTML()}
    <style>
      /* TODO: Add skin styles here */
    </style>
    <media-container>
      <slot name="media" slot="media"></slot>
      <div class="overlay" aria-hidden="true"></div>
      <div class="controls" data-testid="media-controls">
        <media-play-button class="button icon-button">
          <media-play-icon></media-play-icon>
          <media-pause-icon></media-pause-icon>
        </media-play-button>
        <div class="time-controls">
          <media-current-time-display class="time-display"></media-current-time-display>
          <media-time-range-root class="slider-root">
            <media-time-range-track class="slider-track">
              <media-time-range-progress class="slider-progress"></media-time-range-progress>
              <media-time-range-pointer class="slider-pointer"></media-time-range-pointer>
            </media-time-range-track>
            <media-time-range-thumb class="slider-thumb"></media-time-range-thumb>
          </media-time-range-root>
          <media-duration-display class="time-display"></media-duration-display>
        </div>
        <media-popover-root open-on-hover delay close-delay>
          <media-popover-trigger>
            <media-mute-button class="button icon-button volume-button">
              <media-volume-high-icon></media-volume-high-icon>
              <media-volume-low-icon></media-volume-low-icon>
              <media-volume-off-icon></media-volume-off-icon>
            </media-mute-button>
          </media-popover-trigger>
          <media-popover-positioner side="top" side-offset>
            <media-popover-popup>
              <media-volume-range-root class="slider-root" orientation="vertical">
                <media-volume-range-track class="slider-track">
                  <media-volume-range-progress class="slider-progress"></media-volume-range-progress>
                </media-volume-range-track>
                <media-volume-range-thumb class="slider-thumb"></media-volume-range-thumb>
              </media-volume-range-root>
            </media-popover-popup>
          </media-popover-positioner>
        </media-popover-root>
        <media-fullscreen-button class="button icon-button">
          <media-fullscreen-enter-icon></media-fullscreen-enter-icon>
          <media-fullscreen-exit-icon></media-fullscreen-exit-icon>
        </media-fullscreen-button>
      </div>
    </media-container>
  `;
}

export class MediaSkinDefaultCompiled extends MediaSkin {
  static getTemplateHTML: () => string = getTemplateHTML;
}

customElements.define('media-skin-default-compiled', MediaSkinDefaultCompiled);
