packages:
  - 'packages/build-tools/*'
  - packages/build-tools/vjs-compiler/test/e2e/app
  - 'packages/core/*'
  - 'packages/html/*'
  - 'packages/react/*'
  - 'packages/react-native/*'
  - 'examples/*'
  - website
minimumReleaseAge: 1440
