export { parseCandidate, parseVariant } from './candidate.js'
export type { Candidate, Variant, ArbitraryUtilityValue, NamedUtilityValue, CandidateModifier } from './candidate.js'
export { createSimplifiedDesignSystem } from './design-system.js'
export type { DesignSystem } from './design-system.js'
export { segment } from './segment.js'
export { decodeArbitraryValue } from './decode-arbitrary-value.js'
export { isValidArbitrary } from './is-valid-arbitrary.js'
export * as ValueParser from './value-parser.js'