/**
 * Auto-generated by VJS-10 Transpilation System
 * Engine: LLM
 * Source: .mock-test-output/MediaSkinTest.tsx
 * Generated: 2025-09-19T20:37:26.436Z
 *
 * DO NOT EDIT - This file will be overwritten
 */
import '@vjs-10/html-icons';
export function getTemplateHTML() {
  return /* html */ `
  
    <div className="media-container">
      {children}
      <button className="play-button">
        <PlayIcon />
        <PauseIcon />
      </button>
    </div>
  );
};

export default MediaSkinTest;